feat: commitlint setup [#18]
anjaliahlawat/amazon-login-script pull request #29
Opened 2021-03-22 10:20 UTC by anjaliahlawat

2021-03-22 10:27 UTC, h2grover requested changes
@anjaliahlawat I think we are not on the same page, can you please let me know why I asked you to install husky and commitLint ? And is the usage of these packages?

2021-03-22 10:29 UTC, anjaliahlawat commented
@h2grover I think they help in improving and linting the commit messages.

2021-03-22 10:33 UTC, anjaliahlawat commented
@h2grover https://commitlint.js.org/#/guides-ci-setup. This link is for linting CI servers. Shall I do this setup as well?

2021-03-22 10:41 UTC, anjaliahlawat commented
@h2grover  I guess we are trying to do something like this - https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/

2021-03-22 10:47 UTC, h2grover commented
@anjaliahlawat 

> @h2grover https://commitlint.js.org/#/guides-ci-setup. This link is for linting CI servers. Shall I do this setup as well?

No

2021-03-22 10:49 UTC, h2grover commented
> @h2grover I guess we are trying to do something like this - https://www.freecodecamp.org/news/how-to-add-commit-hooks-to-git-with-husky-to-automate-code-tasks/

yes, so how are you achieving this with your code base?


Please run commitLint in pre-commit husky hook

2021-03-22 13:34 UTC, anjaliahlawat commented
I observed that in pre-commit hooks, last commit message was linted but when I used commit-msg hooks, with the commitlint command it was linting current message. Is this behaviour alright?

2021-03-23 09:24 UTC, h2grover requested changes

2021-03-23 09:24 UTC, h2grover commented on package.json
> +  "commitlint": {
Let's add these rules in the `commitlint.config.js` file

2021-03-23 09:24 UTC, h2grover commented on package.json
> +        "issuePrefixes": ["[#]"]
We should not enforce this, `"references-empty": [2, "never"]` is sufficient.

2021-03-23 09:24 UTC, h2grover commented on package.json
> +    "dotenv": "^8.2.0",
Remove whitespace.

2021-03-23 09:24 UTC, h2grover commented on package.json
> +    "postinstall": "husky install"
what is this for? I guess it is not needed plz remove it.

2021-03-23 09:24 UTC, h2grover commented on package.json
> +      "pre-commit": "echo checking commit",
Why outputting on console? Please remove.

2021-03-23 09:24 UTC, h2grover commented on package.json
> +      "references-empty": [2, "never"]
lets add https://commitlint.js.org/#/reference-rules?id=type-enum also

2021-03-23 13:27 UTC, h2grover reviewed
LGTM 👍  but can you please update the PR title manually, it should have same format as commit.

2021-03-23 14:41 UTC, anjaliahlawat commented
@h2grover Please check the pr title. If the format's fine, I will merge this pull request.

2021-03-23 14:49 UTC, h2grover commented
@anjaliahlawat I have updated the title, the first letter should not be capatial. 

> @h2grover Please check the pr title. If the format's fine, I will merge this pull request.

This is your repo so you have merging rights but please do not merge the PR, that is my job to do.

2021-03-23 14:49 UTC, h2grover approved these changes

2021-03-23 14:49 UTC, merged