refactor: changed files name as per camel casing [#22]
anjaliahlawat/amazon-login-script pull request #34
Opened 2021-03-23 05:46 UTC by anjaliahlawat

2021-03-24 09:39 UTC, h2grover commented
@anjaliahlawat please merge `main` and resolve conflicts.
Make sure, don't force push your commits or create new PR.

2021-03-24 09:41 UTC, h2grover commented
here is the link 
https://www.perforce.com/blog/vcs/git-rebase-vs-merge-which-better

I want to you to perform `git merge`

2021-03-24 14:06 UTC, h2grover requested changes
@anjaliahlawat 
Your last commit is not correct, please reset to the last commit and try it again and before pushing please post the `git log` output from the local machine.

The commit should look something like this.
![image](https://user-images.githubusercontent.com/28951570/112323704-0b93eb00-8cd8-11eb-99c3-8ecc6aa0bba5.png)

2021-03-24 14:06 UTC, h2grover commented on src/tests/globalHooks.js
> +    await test.cleanUp()
@anjaliahlawat why `afterSpec` is removed?

2021-03-24 14:58 UTC, anjaliahlawat commented on src/tests/globalHooks.js
> +    await test.cleanUp()
@h2grover 

> @anjaliahlawat
> Your last commit is not correct, please reset to the last commit and try it again and before pushing please post the `git log` output from the local machine.
> 
> The commit should look something like this.
> ![image](https://user-images.githubusercontent.com/28951570/112323704-0b93eb00-8cd8-11eb-99c3-8ecc6aa0bba5.png)

@h2grover I read in documentation that reset should only be used when you're working alone on the repo. But in collaboration revert should be used. So I think I should use revert here

2021-03-24 15:30 UTC, h2grover commented on src/tests/globalHooks.js
> +    await test.cleanUp()
@anjaliahlawat 
That's correct, but here I don't want your revert commit in the logs so that's why I asked to reset the previous commit and merge the `main` branch again. 

Revert/rollback is needed when there was a bug in the production and we want to revert that change. In our case, we will mostly use reset.

2021-03-24 15:44 UTC, h2grover requested changes
I can see filenames are not changed yet. 
https://github.com/anjaliahlawat/amazon-login-script/tree/hands-on/%2322-camel-case/src/tests/amazon/step_definition

Please review all the file names, another thing please start with a capital word while naming a file in case of a class.

2021-03-24 15:44 UTC, h2grover commented
Please rename the PR titile.

2021-03-24 16:57 UTC, anjaliahlawat commented
> I can see filenames are not changed yet.
> https://github.com/anjaliahlawat/amazon-login-script/tree/hands-on/%2322-camel-case/src/tests/amazon/step_definition
> 
> Please review all the file names, another thing please start with a capital word while naming a file in case of a class.

![structure](https://user-images.githubusercontent.com/29258626/112351109-9b915f00-8cef-11eb-8de2-b5f6eebeca44.jpg)
According to this, loggedInHomePage.spec -> login.spec
signInPageValidation.spec -> loginPage.spec
 
I changed these names. But the rest are as per the structure provided.

2021-03-24 17:06 UTC, anjaliahlawat commented
> Please rename the PR titile.

I think I forgot about the instruction you provided for naming of PRs. Can you please remind me? Is it as per the name of the ticket assigned ?

2021-03-25 06:03 UTC, h2grover commented
> > Please rename the PR titile.
> 
> I think I forgot about the instruction you provided for naming of PRs. Can you please remind me? Is it as per the name of the ticket assigned ?

Structure will be same as the commit one

2021-03-25 06:07 UTC, h2grover commented
@anjaliahlawat i can still see few files name in snake casing can you please push a commit for the same.

2021-03-25 09:22 UTC, h2grover commented
@anjaliahlawat please resolve conflicts.

2021-03-25 09:40 UTC, anjaliahlawat commented
> @anjaliahlawat i can still see few files name in snake casing can you please push a commit for the same.

@h2grover I wonder if folder names should also be in camel case.

2021-03-25 09:43 UTC, h2grover commented
> I wonder if folder names should also be in camel case.

@anjaliahlawat we can skip this for now. 

Also please check PR title on your own moving forward.

2021-03-25 09:47 UTC, anjaliahlawat commented
> > I wonder if folder names should also be in camel case.
> 
> @anjaliahlawat we can skip this for now.
> 
> Also please check PR title on your own moving forward.

I wonder if pr title is named after last commit or something meaningful as per the commit structure. Please pr title now

2021-03-31 13:53 UTC, merged

2021-03-31 13:53 UTC, h2grover approved these changes