refactor: take screenshot on test failure [#23]
anjaliahlawat/amazon-login-script pull request #35
Opened 2021-03-23 06:24 UTC by anjaliahlawat

2021-03-23 06:47 UTC, h2grover requested changes

2021-03-23 06:47 UTC, h2grover commented on src/tests/amazon/step_definition/login_page_implementation.js
> +})
Yup, this is the right way

2021-03-23 06:47 UTC, h2grover commented on src/lib/helper.js
> +    },
Lets make this a class, so that we dont have to pass `page` object in every function and rename this file to `pagewrapper.js`. we will create our custom methods moving forward.

2021-03-23 06:49 UTC, anjaliahlawat commented on src/lib/helper.js
> +    },
Shall I make another pr for this?

2021-03-23 15:52 UTC, h2grover requested changes

2021-03-23 15:52 UTC, h2grover commented on src/tests/TestBase.js
>  const puppeteer = require('puppeteer');
let's rename this file `setup.js`

2021-03-23 15:52 UTC, h2grover commented on src/tests/amazon/step_definition/login_page_implementation.js
> +    helper = new Helper(gauge.dataStore.specStore.get("page"))
store this in variable `gauge.dataStore.specStore.get("page")` and then use that.

2021-03-23 15:52 UTC, h2grover commented on src/tests/amazon/step_definition/login_page_implementation.js
> +const Helper = require("../../../lib/pageWrapper");
please use `PageWrapper` instead of `Helper`

2021-03-23 15:52 UTC, h2grover commented on src/tests/amazon/step_definition/login_page_implementation.js
> +})
just noticed, let move this to global hooks files

2021-03-23 15:52 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
need to understand why you have extended the PageWrapper class? 
Why not use it like this in the constuctor? 
```
pageWrapper = new PageWrapper(page);
```

2021-03-24 06:12 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
I thought this was a better way to refactor our code. Instead of declaring Helper class in every step definition file, why not extend it in AmazonLoginPage class.

2021-03-24 06:17 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@anjaliahlawat 

> why not extend it in AmazonLoginPage class.


that's my question, why to use extend ?

Can you please read about it and post the usage of both?

I am.not saying you did wrong but please let me know the difference between both and its usages

2021-03-24 07:07 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
Extend Keyword - It is used for inheritance in javascript. The child class will inherit all the properties of parent class. 

Explanation: If AmazonLoginPage inherits all the properties of pagewrapper class, then we don't need to initialize pagewrapper class in all step definition files. We can simply fetch the properties of it from amazonLogin object. Hence we only need to initialize pagewrapper class in our AmazonLoginPage class.
This is the benefit of inheritance - code reusability.

Problem - This creates coupling in the two classes and I guess it's not helpful when we perform tests. Plus, inheritance is not considered a good approach overall.
For reference - https://codeburst.io/inheritance-is-evil-stop-using-it-6c4f1caf5117.( this gave me some insights).

Solution -  
Reduce coupling - following DIP( Dependency Inversion Principle)
This is what I think is what we should do -
https://github.com/ryanmcdermott/clean-code-javascript#dependency-inversion-principle-dip

And according to this, we shouldn't call constructor of one class from another class.

Let me know what you think?

2021-03-24 07:46 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@anjaliahlawat Let's try this using an example. 

Here is the use case:
- You are in step definition class
- you are accessing those page function in the step definition 

Please post an example with both the `extends` keyword and  initializing an object

2021-03-24 07:51 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@h2grover  Shall I make changes in the file as per both the scenario and push it here?
and example of initializing the object the way you suggested above?

2021-03-24 08:00 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@anjaliahlawat 
No you don't have to push any changes, please post it in the comments.

You have write minimum code to demonstrate the example.

2021-03-24 08:02 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
First you should understand, where my questions are coming from.

2021-03-24 08:26 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
Example - using extend keyword
```
//AmazonLoginPage class module.exports=class AmazonLoginPage extends PageWrapper{ constructor(page){ this.page = page } }
```
```
//step implementation
var AmazonLoginPage = require("../pages/AmazonLoginPage")
var amazonLogin = {}

beforeSpec(async () => {
let page = gauge.dataStore.specStore.get("page")
amazonLogin = new AmazonLoginPage(page)
})

step("Verify text label is visible", async function(text) {
assert.ok(await amazonLogin.checkIfTextExist(text))
})
```

2021-03-24 08:30 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
Example - initializing pagewrapper class within amazonLoginPage constructor
```
//AmazonLoginPage class
let pageWrapper = {}

module.exports=class AmazonLoginPage {
   constructor(page){
     this.page = page
     pageWrapper = new PageWrapper(page)
   }
}
```
```
//step definition
var amazonLogin = {}
var pageWrapper = {}

beforeSpec(async () => {
let page = gauge.dataStore.specStore.get("page")
amazonLogin = new AmazonLoginPage(page);
pageWrapper = new PageWrapper(page)
})
step("Open amazon website", async function(){
await amazonLogin.visitAmazonHome()
await amazonLogin.signIn()
})
step("Verify text label is visible", async function(text) {
assert.ok(await pageWrapper.checkIfTextExist(text))
})
```

2021-03-24 09:02 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@anjaliahlawat let's use the second approach mentioned here https://github.com/anjaliahlawat/amazon-login-script/pull/35#discussion_r600266395
This way we will be able to differentiate between the `pagewrapper` function and functions present in the respective page class. Also, we will be dealing with `components` in the future so we should keep it clean and simple.

Please push a commit for the same.

2021-03-24 09:16 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@h2grover My last commits were as per the #35. Please review them.

2021-03-24 09:17 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@h2grover https://github.com/anjaliahlawat/amazon-login-script/pull/35#discussion_r600220672
You didn't post any thoughts on it. Please tell me if I am getting this right.

2021-03-24 09:29 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.js
> +module.exports=class AmazonLoginPage extends Helper{
@anjaliahlawat yes, that is somehow correct and applies in our case also. Also if we are inheriting any class we can override it in the subclass, so as to avoid overriding and to isolate the functionalities of pagewrapper we are doing do.

You will understand the POM concept as you move forward so let's not worry about that.

2021-03-24 09:33 UTC, h2grover approved these changes
LGTM

2021-03-24 09:34 UTC, merged