file: readme.md file added [#20]
anjaliahlawat/amazon-login-script pull request #36
Opened 2021-03-23 08:15 UTC by anjaliahlawat

2021-03-31 14:00 UTC, h2grover requested changes
Its better to add commands from gauge like, how to run in parallel , tags specific.

2021-03-31 14:00 UTC, h2grover commented on README.md
> +- Node.js
please specify the node version which is required and also link the nvm installation guide. It is always better to use nvm to install the different node versions.

2021-03-31 14:00 UTC, h2grover commented on README.md
> +- Package manager - npm or yarn
link the `yarn` installation page. `npm` is not needed so you can remove it.

2021-03-31 14:00 UTC, h2grover commented on README.md
> +$ yarn add
shouldn't it be `yarn` or `yarn install` ?

2021-03-31 14:00 UTC, h2grover commented on README.md
> +$ yarn test
this will not come under installation step

2021-03-31 14:00 UTC, h2grover commented on README.md
> +
remove extra lines.

2021-04-01 06:14 UTC, h2grover commented on src/lib/PageWrapper.js
> +const { v4: uniqueId } = require("uuid");
@anjaliahlawat how come these changes are coming here?
it should already be in `main` branch

2021-04-01 06:16 UTC, h2grover commented on src/lib/PageWrapper.js
> +const { v4: uniqueId } = require("uuid");
![image](https://user-images.githubusercontent.com/28951570/113251338-beb7a200-92df-11eb-96ed-fa6a7d1d0b9d.png)


Why you have force pushed your changes?

2021-04-01 06:23 UTC, anjaliahlawat commented on src/lib/PageWrapper.js
> +const { v4: uniqueId } = require("uuid");
I did pull the changes. But some linting errors were still shown when I tried to commit so I fixed them here again.

2021-04-01 06:24 UTC, anjaliahlawat commented on src/lib/PageWrapper.js
> +const { v4: uniqueId } = require("uuid");
> ![image](https://user-images.githubusercontent.com/28951570/113251338-beb7a200-92df-11eb-96ed-fa6a7d1d0b9d.png)
> 
> Why you have force pushed your changes?

I committed incomplete changes. So I forced it back to previous commit and completed the changes and then pushed it here.

2021-04-01 06:27 UTC, h2grover commented on src/lib/PageWrapper.js
> +const { v4: uniqueId } = require("uuid");
please do not force push any changes moving forward.

2021-04-01 06:31 UTC, h2grover approved these changes
@anjaliahlawat 
I am merging this PR for now. But moving forward any refactoring or enhancements that are not PR related should be done in a separate PR first. in this case, it was linting changes. 

Correct process:
1. Create separate PR for the lint fixes
1. I will merge that PR after review
1. You will then merge `main` branch to this PR 
1. Then this PR will get merged.

2021-04-01 06:31 UTC, merged