feat: eslint integrated [#24]
anjaliahlawat/amazon-login-script pull request #37
Opened 2021-03-24 10:27 UTC by anjaliahlawat

2021-03-24 10:37 UTC, h2grover requested changes

2021-03-24 10:37 UTC, h2grover commented on .eslintrc.json
> +        "wrap-iife": "off",
@anjaliahlawat please airbnb eslint rule guide. It doesn't make sense to write so many custom rules

2021-03-24 12:00 UTC, anjaliahlawat commented on .eslintrc.json
> +        "wrap-iife": "off",
@h2grover I am going through the rules of eslint. But to be specific, which rules should I add ?

2021-03-24 12:04 UTC, h2grover commented on .eslintrc.json
> +        "wrap-iife": "off",
@anjaliahlawat what do you mean by that?
Please use default rules provided by airbnb plugin for now.

2021-03-24 13:02 UTC, anjaliahlawat commented on .eslintrc.json
> +        "wrap-iife": "off",
@h2grover I just thought of adding custom rules like camel casing etc

2021-03-24 13:04 UTC, h2grover requested changes

2021-03-24 13:04 UTC, h2grover commented on package.json
> +    "eslint-plugin-jsx-a11y": "^6.4.1",
Why this?

2021-03-24 13:04 UTC, h2grover commented on package.json
> +    "eslint-plugin-react": "^7.23.1",
Why this?

2021-03-24 13:04 UTC, h2grover commented on src/tests/amazon/step_definition/login_implementation.js
> +beforeSpec(async function(){
Why not arrow function here?

2021-03-24 13:04 UTC, h2grover commented on yarn-error.log
>  Arguments:
Add this to gitignore and remove the file

2021-03-24 13:04 UTC, h2grover commented on src/tests/globalHooks.js
> +        page = await setup.createPage();
Is it because of linting done by eslint?

2021-03-24 13:04 UTC, h2grover commented on package.json
> +    "eslint-plugin-import": "^2.22.1",
What is the usage?

2021-03-24 13:04 UTC, h2grover commented on package.json
> +    "lint": "eslint src/"
Use node modules eslint and run it on root folder.

2021-03-24 13:06 UTC, anjaliahlawat commented on package.json
> +    "eslint-plugin-react": "^7.23.1",
As I tried to run eslint command from terminal, it threw this error. I googled it but then it only worked when I added these dependencies.

2021-03-24 13:07 UTC, anjaliahlawat commented on package.json
> +    "eslint-plugin-jsx-a11y": "^6.4.1",
@h2grover I was supposed to config airbnb with eslint. So I found this solution online.

2021-03-24 13:09 UTC, anjaliahlawat commented on src/tests/amazon/step_definition/login_implementation.js
> +beforeSpec(async function(){
@h2grover I guess I changed it when trying to resolve errors when I ran eslint. No problem I can switch it back to arrow functions. I was trying to understand how eslint is responding to different version of ECMA.

2021-03-24 13:15 UTC, anjaliahlawat commented on src/tests/globalHooks.js
> +        page = await setup.createPage();
Yeah maybe. Also, I have added a support for es5 and es6 currently. Should I only use one of them?

2021-03-24 13:35 UTC, h2grover commented
@anjaliahlawat I have added commit for `eslint` config and with `airbnb`. I have also added `prettier` plugin which I was going to ask you next but don't worry on that now.

Now you have to just run `yarn run lint` command on local and resolve those errors. Which are something like this

![image](https://user-images.githubusercontent.com/28951570/112319126-c2da3300-8cd3-11eb-986e-071ae4a1e956.png)

2021-03-24 13:37 UTC, h2grover commented on yarn-error.log
>  Arguments:
Also, push commit to remove this file

2021-03-24 13:39 UTC, h2grover commented on package.json
> +    "eslint-plugin-jsx-a11y": "^6.4.1",
@anjaliahlawat 
not every solution is recommended and best of our interest. Please think twice before pushing any random code. And be prepared for the answers. You cannot say "**I found this solution online**"

2021-03-24 13:52 UTC, anjaliahlawat commented on package.json
> +    "eslint-plugin-jsx-a11y": "^6.4.1",
Yes, thanks. I'll keep that in mind.

2021-03-25 06:07 UTC, h2grover commented
@anjaliahlawat Please donot work in parallel, work on this ticket first

2021-03-25 08:39 UTC, h2grover requested changes

2021-03-25 08:39 UTC, h2grover commented on src/lib/PageWrapper.js
> +  getUrl() {
@anjaliahlawat  this should be async function

2021-03-25 08:39 UTC, h2grover commented on yarn-error.log
>  Arguments:
@anjaliahlawat why this file is still here after mentioning twice?

2021-03-25 08:54 UTC, h2grover commented
@anjaliahlawat another tip, when I request changes then please push all the commits at once not one by one.

2021-03-25 08:54 UTC, h2grover commented
Let me know if this is https://github.com/anjaliahlawat/amazon-login-script/pull/37#issuecomment-806476947 not clear

2021-03-25 09:04 UTC, anjaliahlawat commented on src/lib/PageWrapper.js
> +  getUrl() {
I don't think so. Actually eslint showed redundant await error here. So I removed async-await from here and ran tests to check. The tests worked fine. So I think we don't need to make it async fn.

2021-03-25 09:06 UTC, anjaliahlawat commented on yarn-error.log
>  Arguments:
My apologies. I forgot to remove it from the staging area.

2021-03-25 09:07 UTC, anjaliahlawat commented
All changes are done from my side. Please review them.

2021-03-25 09:21 UTC, merged