fix: linting errors fixed [#38]
anjaliahlawat/amazon-login-script pull request #41
Opened 2021-03-25 11:49 UTC by anjaliahlawat

2021-03-25 11:58 UTC, anjaliahlawat commented
@h2grover Please check this out.
https://duncanleung.com/profile-measure-find-remove-slow-eslint-rules/
I checked it on my system and it seems that prettier is actually taking 82% of the total time spent. 
Maybe I should configure prettier like this. 
What do you think?

2021-03-25 12:56 UTC, h2grover commented
@anjaliahlawat lets use eslint cache then. Please check that

2021-03-25 13:43 UTC, anjaliahlawat commented
![lint-errors](https://user-images.githubusercontent.com/29258626/112482265-e23d9280-8d9d-11eb-81c6-a02337fe24a9.jpg)
@h2grover In my system, on linting,it is showing around 4800 errors. Is your system not showing these errors?

2021-03-25 14:37 UTC, anjaliahlawat commented
@h2grover I added .eslintignore file and added some directories which I thought don't require linting. Now  I am not getting any errors. Please review it and let me know if it's the right way to go.

2021-03-25 15:13 UTC, h2grover requested changes

2021-03-25 15:13 UTC, h2grover commented on .eslintignore
> +
Please add node_modules also

2021-03-25 15:50 UTC, anjaliahlawat commented on .eslintignore
> +
In eslint documentation, it is given that by default node_modules and any files or directories starting with . are ignored while linting.

2021-03-25 16:06 UTC, h2grover commented on .eslintignore
> +
Ok thanks for cross checking @anjaliahlawat.

Thats' weird I can see errors on my machines, I will cross check it tomorrow then

2021-03-31 13:50 UTC, h2grover approved these changes
LGTM

2021-03-31 13:50 UTC, merged