fix: updated env variables [#46]
anjaliahlawat/amazon-login-script pull request #48
Opened 2021-04-02 11:44 UTC by anjaliahlawat

2021-04-02 13:26 UTC, anjaliahlawat commented
@h2grover https://github.com/anjaliahlawat/amazon-login-script/runs/2253873070?check_suite_focus=true

I have checked that github secrets are still undefined in the script. Please review it and let me know if there are any changes to be done.

2021-04-02 18:00 UTC, anjaliahlawat commented
@h2grover https://github.com/anjaliahlawat/amazon-login-script/runs/2255415691?check_suite_focus=true
![workflow](https://user-images.githubusercontent.com/29258626/113441133-5960cf80-940b-11eb-8974-0d875b25fd1e.jpg)
Interestingly in this workflow, when I placed env outside of jobs and tried to print one of the github secrets, I got these "*" in console. And normally I was getting these values as undefined. 

So, as per this, I guess now these astricks means that values of github secrets are accessible and if that's the case, then placing env here is correct. 

Please review these changes and let me know what you think.

2021-04-05 04:48 UTC, h2grover commented
@anjaliahlawat let me know when you done testing or fixing bugs

2021-04-07 04:27 UTC, h2grover requested changes

2021-04-07 04:27 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    const dirs = ["reports", "html-report", "images", "screenshots", "failed"];
We have better way to do this, instead of taking array. Can you please explore more.

2021-04-07 04:27 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.ts
> +    await this.page.type("#ap_email", process.env.AMAZON_USERNAME!);
@anjaliahlawat as you noticed i made the enhancement regarding process env implementation in different files. Can you follow the same patter in all the such places

2021-04-07 04:27 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    let baseDir = "./";
Please create different file i.e pathUtils. As page wrapper is not responsible for creating dir.

2021-04-07 04:27 UTC, h2grover commented on src/tests/amazon/step_definition/LoginPage.ts
> +    await pageWrapper.waitForElementToDisappearByText(notificationText, 120000);
You can reduce the time here if you want. Lets reduce it to 1 min

2021-04-07 04:44 UTC, anjaliahlawat commented on src/lib/PageWrapper.ts
> +    const dirs = ["reports", "html-report", "images", "screenshots", "failed"];
```
const structure = {
  reports: {
    "html-report": {
      images: {
        screenshots: {
          failed: {},
        },
      },
    },
  },
};
```
I have observed this structure also for defining directories. Is this a better one?

2021-04-07 04:51 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    const dirs = ["reports", "html-report", "images", "screenshots", "failed"];
I am sure about this either, i guess we can provide path and split it by `/`  and create directories.

2021-04-07 04:51 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    const dirs = ["reports", "html-report", "images", "screenshots", "failed"];
Providing array or object is just not right

2021-04-07 06:27 UTC, h2grover requested changes

2021-04-07 06:27 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.ts
>        waitUntil: "networkidle0",
Can't we remove `!` ? I think we can. Please check.

2021-04-07 06:27 UTC, h2grover commented on src/lib/pathUtils.ts
> +export default createDir;
Please export the function in object. So that we can add other functions in the export variable.

2021-04-07 06:36 UTC, anjaliahlawat commented on src/lib/pathUtils.ts
> +export default createDir;
@h2grover I tried that eslint is showing error  - `import/prefer-default-export`.

2021-04-07 07:22 UTC, anjaliahlawat commented on src/tests/amazon/pages/AmazonLoginPage.ts
>        waitUntil: "networkidle0",
I am thinking that maybe I can use `if condition` to check if env is set and then proceed further.
A function to be called before running these tests where all important `env` variables are set or not.

2021-04-07 07:40 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.ts
>        waitUntil: "networkidle0",
@anjaliahlawat 
Have you gone through all my changes, which I did before? I don't think so!

2021-04-07 08:32 UTC, h2grover commented on src/tests/amazon/pages/AmazonLoginPage.ts
>        waitUntil: "networkidle0",
@anjaliahlawat 
![image](https://user-images.githubusercontent.com/28951570/113835108-42becd80-97a9-11eb-94e1-ba871615c8c4.png)


After adding it in `global.d.ts` file

![image](https://user-images.githubusercontent.com/28951570/113835200-5ec26f00-97a9-11eb-8ef5-c95d2d4ba9f0.png)


We have to define the type of env variables. Please do this for all the env variables and add them to the global file.

2021-04-07 08:34 UTC, h2grover commented on src/global.d.ts
> +    readonly PUPPETEER_TIMEOUT: string;
If these variables are not added here then typescript will throw an error and say "PUPPETEER_TIMEOUT" might be undefined.

@anjaliahlawat 
We should not be worried if the env variable is set or not as we will get an error on run time. 
And there is very little chance for that as we are testing on local in a similar fashion. 

Let me know in case of any concerns.

2021-04-07 08:35 UTC, h2grover commented on src/global.d.ts
> +    readonly PUPPETEER_TIMEOUT: string;
This is a prerequisite that we have to consider.

2021-04-07 08:35 UTC, h2grover commented on .github/workflows/amazon.yml
> +    branches: [ hands-on/#46-env-var ]
please disable it

2021-04-07 08:37 UTC, h2grover requested changes
Need minor changes, then I will merge it. Please check above comments.

2021-04-07 09:09 UTC, h2grover approved these changes

2021-04-07 09:09 UTC, merged