feat: link added for screenshot in report [#49]
anjaliahlawat/amazon-login-script pull request #50
Opened 2021-04-07 13:07 UTC by anjaliahlawat

2021-04-07 13:10 UTC, h2grover commented
@anjaliahlawat can you please post the screenshot of the html report.

2021-04-07 13:11 UTC, h2grover approved these changes

2021-04-07 13:16 UTC, anjaliahlawat commented
> @anjaliahlawat can you please post the screenshot of the html report.

screenshot of the page displaying resulted hyperlink of screenshot in html-report?

2021-04-07 13:17 UTC, h2grover commented
> > @anjaliahlawat can you please post the screenshot of the html report.
> 
> screenshot of the page displaying resulted hyperlink of screenshot in html-report?

Yes and also the screenshot which is opened in the browser with path in the address bar

2021-04-07 13:21 UTC, anjaliahlawat commented
Html report screenshot -
![image](https://user-images.githubusercontent.com/29258626/113873161-2d11ce00-97d2-11eb-9fc9-8bfba2a06f65.png)

screenshot -
![image](https://user-images.githubusercontent.com/29258626/113873253-4581e880-97d2-11eb-9bb7-8e2827b81a64.png)

2021-04-07 13:30 UTC, h2grover requested changes
Anjali, we have to attach screenshot in case of failure only. In this case it will be attached even when we call takescreenshot function

2021-04-07 14:06 UTC, anjaliahlawat commented
> Anjali, we have to attach screenshot in case of failure only. In this case it will be attached even when we call takescreenshot function

Oh right. Then I should add this in afterspec func under if condition. But since I need full path for screenshot, I should define this path in env. What do you think?

2021-04-08 04:26 UTC, h2grover requested changes
Anjali instead of passing isFailed argument, why don't you pass fullPath?
If fullPath is passed then we ill use that path otherwise takescreenshot will create its own path.

2021-04-08 04:28 UTC, h2grover commented
Default path in the screenshot function will be reports/html-report/images/screenshots/

2021-04-08 05:31 UTC, h2grover requested changes

2021-04-08 05:31 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    let fullPath: string;
please remove the redundant code

2021-04-08 05:31 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    let fullPath: string;
```
await this.page.screenshot({
        path: fullPath,
      });
```

can be used only once.

2021-04-08 05:49 UTC, h2grover requested changes
please try this and try to remove the redundant code after reading it twice.

2021-04-08 05:49 UTC, h2grover commented on src/lib/PageWrapper.ts
> +    }
you can also do like this.
```
  async takeScreenShot(scrPath?: string): Promise<void> {
    const name = uniqueId();
    const screenshotDirPath = scrPath || "reports/html-report/images/screenshots";
    await createDir(screenshotDirPath);
    const screenshotFullPath = join(resolve("."), scrPath, `/${name}.png`);
    await this.page.screenshot({
      path: screenshotFullPath,
    });
  }
```

2021-04-08 06:31 UTC, h2grover commented
@anjaliahlawat have you tested the `takeScrenshot` function with both the possibilities ?

2021-04-08 06:34 UTC, anjaliahlawat commented
> @anjaliahlawat have you tested the `takeScrenshot` function with both the possibilities ?

Yes. It was working in both the cases.

2021-04-08 06:35 UTC, h2grover approved these changes

2021-04-08 06:35 UTC, merged